sudo: true
dist: trusty
language: node_js
node_js:
- '10'
before_install:
- if [[ `npm -v` != 5* ]]; then npm install --unsafe-perm --verbose -g npm@5; fi
install:
- npm install
notifications:
  email: false
